language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.6"
services:
  - redis-server
before_script:
  - psql -c "CREATE USER nex WITH PASSWORD '[passwd]'"
  - psql -U postgres postgres -c "CREATE DATABASE sgd WITH OWNER nex ENCODING 'UTF8'"
  - psql -U postgres sgd -c "CREATE ROLE CURATOR"
  - psql -U postgres sgd -c "CREATE USER OTTO WITH PASSWORD '[passwd]'"
  - psql -U postgres sgd -c "GRANT CURATOR to OTTO"
  - psql -U postgres sgd -c "CREATE SCHEMA nex AUTHORIZATION nex"
  - psql -U postgres sgd -c "GRANT USAGE ON SCHEMA nex TO CURATOR"
script:
  - printf 'export NEX2_URI="postgresql://nex:passwd@localhost/sgd"\n' > test_variables.sh
  - printf 'export ES_URI="http://localhost:9200/"\n' >> test_variables.sh
  - printf 'export S3_BUCKET="S3 BUCKET"\n' >> test_variables.sh
  - printf 'export S3_SECRET_KEY="S3 SECRET KEY"\n' >> test_variables.sh
  - printf 'export S3_ACCESS_KEY="S3 ACCESS KEY"\n' >> test_variables.sh
  - source test_variables.sh && nosetests -s
